routes/album_routes.py
from flask import Blueprint, render_template, redirect, url_for
from datetime import datetime
from forms.album_forms import CreateAlbumForm
from flask_login import current_user

album_blueprint = Blueprint('album_blueprint', __name__)

@album_blueprint.route('/test-insert', methods=['GET', 'POST'])
def testInsert():
    from models.Member import Member
    from models.Album import Album
    from app import db
    member = Member.query.get(1)
    album = Album(name="Test Album", owner_id=member.id, created=datetime.utcnow()) # Pass the member object instead of member.id

    db.session.add(album)
    db.session.commit()
    return "album created successfully"

@album_blueprint.route('/test-delete', methods=['GET', 'POST'])
def testDelete():
    from models.Member import Member
    from models.Album import Album
    from app import db
    album = Album.query.filter_by(name="Test Album").first()

    if not album:
        return "could not get album"

    db.session.delete(album)
    db.session.commit()

    return 'album was deleted'

@album_blueprint.route('/create', methods=['GET', 'POST'])
def createAlbum():
    from models.Album import Album
    from app import db

    # Check if the user is logged in
    if not current_user.is_authenticated:
        return redirect(url_for('member_blueprint.signin'))

    form = CreateAlbumForm()
    if form.validate_on_submit():
        album = Album(
            name = form.album_name.data,
            created = datetime.utcnow(),
            owner_id=current_user.id
        )
        db.session.add(album)
        db.session.commit()
        return redirect(url_for('success'))

    return render_template('create_album.html', title='Create Album', form=form)

routes/member_routes.py
from curses import flash
from flask import Blueprint, render_template, redirect, url_for
from flask_login import login_user
from forms.member_forms import LoginForm, RegistrationForm

member_blueprint = Blueprint('member_blueprint', __name__)

@member_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    from models.Member import Member
    from app import db
    form = RegistrationForm()
    if form.validate_on_submit():
        member = Member(
            first_name=form.first_name.data,
            last_name=form.last_name.data,
            email=form.email.data,
            dob=form.dob.data,
            hometown=form.hometown.data,
            gender=form.gender.data
        )
        member.set_password(form.password.data)
        db.session.add(member)
        db.session.commit()
        return redirect(url_for('member_blueprint.signin'))
        
    return render_template('register.html', form=form)

@member_blueprint.route('/signin', methods=['GET', 'POST'])
def signin():
    from models.Member import Member
    form = LoginForm()
    if form.validate_on_submit():
        member = Member.query.filter_by(email=form.email.data).first()
        if member is None or not member.check_password(form.password.data):
            return redirect(url_for('member_blueprint.signin'))
        login_user(member, remember=False)
        return redirect(url_for('success'))
    return render_template('login.html', title='Sign In', form=form)

templates/create_album.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Album</title>
</head>

<body>
    <h1>Create Album</h1>
    <form method="POST" action="{{ url_for('album_blueprint.createAlbum') }}">
        {{ form.csrf_token }}
        {{ form.album_name.label }} {{form.album_name }}
        {{ form.submit }}
    </form>
</body>

</html>

templates/login.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>

<body>
    <h1>Login</h1>
    <form method="POST" action="{{ url_for('member_blueprint.signin') }}">
        {{ form.csrf_token }}
        {{ form.email.label }} {{form.email}}
        {{ form.password.label }} {{form.password}}
        {{ form.submit }}
    </form>
</body>

</html>

templates/register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create User</title>
</head>

<body>
    <h1>Create User</h1>
    <form method="POST" action="{{ url_for('member_blueprint.register') }}">
        {{ form.csrf_token }}
        {{ form.first_name.label }} {{ form.first_name }}<br>
        {{ form.last_name.label }} {{ form.last_name }}<br>
        {{ form.hometown.label }} {{ form.hometown }}<br>
        {{ form.email.label }} {{ form.email }}<br>
        {{ form.dob.label }} {{ form.dob }}<br>
        {{ form.gender.label }} {{ form.gender }}<br>
        {{ form.password.label }} {{ form.password }}<br>
        {{ form.submit }}
    </form>
</body>

</html>

templates/upload_photo.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create User</title>
</head>

<body>
    <h1>Upload a Photo</h1>
    <form method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div>
            {{ form.album.label }}<br>
            {{ form.album }}
        </div>
        <div>
            {{ form.caption.label }}<br>
            {{ form.caption }}
        </div>
        <div>
            {{ form.photo.label }}<br>
            {{ form.photo }}
        </div>
        {{ form.submit }}
    </form>
</body>